### ISSUE TITLE
Remove Composer filesystem port

### ISSUE THREAD

**Issue by raulfraile** [raulfraile/distill#24]
Currently, Distill uses a port of Composer's filesystem to get around rename issue: https://github.com/raulfraile/distill/pull/9

I'm considering removing the port and use the Symfony Filesystem component in next version, but unfortunately the issue https://github.com/symfony/symfony/issues/12533 is not fixed yet. Any comments @weaverryan @javiereguiluz @xabbuh?

**Comment by weaverryan** [comment]
@raulfraile What's your motivation for removing the port? That would basically re-open issue #9 as well, right?

**Comment by raulfraile** [comment]
@weaverryan yeah, that's why I don't want to remove it until https://github.com/symfony/symfony/issues/12533 is fixed. As you pointed out in the PR, this was a temporary fix, and I would like to just rely on the Symfony Filesystem in the next major version.

**Comment by weaverryan** [comment]
It doesn't look like there's even a PR for  symfony/symfony#12533. Obviously, the best-case scenario would be to make that PR with the fix, then happily remove the port from here :).

**Comment by xabbuh** [comment]
I still have the issue on my to do list. I can try to fix it this weekend.
